//! # REST API
//!
//! This interface will provide reduced functionality as opposed to WebSocket [`crate::api::ws`],
//! which should be preferred where possible.
//!
//! All messages are encoded using JSON, such that it can be used in many contexts without
//! requiring external dependencies on CBOR (de)serialisation, as is the case with the WebSocket API.
//!
//! ## `OpenAPI` Specification
//!
//! When the server is running, the API reference (Swagger UI) can be found at
//! [`http://{host}:{port}/api-docs/swagger-ui/`][local-swagger].
//! Alternatively, rapidoc is also available under [`/api-docs/rapidoc`][local-rapidoc], or see the
//! specification itself under [`/api-docs/openapi.json`][local-spec]
//!
//! [local-swagger]: http://127.0.0.1:8080/api-docs/swagger-ui/
//! [local-rapidoc]: http://127.0.0.1:8080/api-docs/rapidoc
//! [local-spec]: http://127.0.0.1:8080/api-docs/openapi.json

use std::net::SocketAddr;

use axum::{
    Json,
    extract::{Path, State},
    http::StatusCode,
    response::IntoResponse,
    routing::any,
};
use tokio::net::TcpListener;
use tracing::info;
use utoipa::OpenApi;
use utoipa_axum::{router::OpenApiRouter, routes};
use utoipa_rapidoc::RapiDoc;
use utoipa_swagger_ui::SwaggerUi;

use crate::{
    api::{ApiState, ModeRequest, UpdateColourRequest, UpdateFixturesRequest, ws::ws_handler},
    config::ServerConfig,
    state::{SharedState, StageMode},
};

const CONFIG_TAG: &str = "Configuration";
const MANUAL_TAG: &str = "Manual Control";

/// Error type returned by some REST API handlers.
///
/// Wraps an internal error ([`anyhow::Error`])
/// and converts it into a 400 [`StatusCode::BAD_REQUEST`] response.
pub struct ApiError(pub anyhow::Error);

type ApiResult<T> = Result<T, ApiError>;

impl IntoResponse for ApiError {
    fn into_response(self) -> axum::response::Response {
        (StatusCode::BAD_REQUEST, self.0.to_string()).into_response()
    }
}

impl<E> From<E> for ApiError
where
    E: Into<anyhow::Error>,
{
    fn from(err: E) -> Self {
        Self(err.into())
    }
}

/// Autogenerated `OpenAPI` docs.
#[derive(OpenApi)]
#[openapi(info(title = "Light Stage API", description = include_str!("README.md")))]
struct ApiDoc;

/// Starts the REST (and WebSocket) API.
///
/// Creates the [`axum`] router, registers REST and WS endpoints, `OpenAPI` docs.
pub async fn start_server(config: ServerConfig, state: SharedState) {
    let api_state = ApiState { state, config };

    let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .route("/ws", any(ws_handler))
        .routes(routes!(get_config))
        .routes(routes!(get_mode, set_mode))
        .routes(routes!(set_lightstage))
        .routes(routes!(set_arc))
        .routes(routes!(set_fixture))
        .routes(routes!(set_fixtures))
        .routes(routes!(manual_trigger))
        .split_for_parts();

    // host swagger / rapidocs
    let app = router
        .merge(SwaggerUi::new("/api-docs/swagger-ui").url("/api-docs/openapi.json", api))
        // the swagger router is already hosting the openapi spec so we can just do:
        .merge(RapiDoc::new("/api-docs/openapi.json").path("/api-docs/rapidoc"))
        // if we drop swagger we would otherwise do:
        // .merge(RapiDoc::with_url(
        //     "/rapidoc",
        //     "/apid-docs/openapi.json",
        //     api,
        // ))
        .with_state(api_state);
    // TODO make base path (ie. `/api/`) configurable

    // from config
    let addr = SocketAddr::new(config.api_ip, config.api_port);
    info!("Starting REST API. Listening on http://{addr}");

    // serve
    let listener = TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

/// Get the server's configuration
///
/// Counterpart to [`crate::api::ws::WsCommand::GetConfig`]
#[utoipa::path(
    get,
    path = "/api/config",
    tag = CONFIG_TAG,
    responses(
        (status = StatusCode::OK, description = "Get config success", body = ServerConfig)
    )
)]
async fn get_config(State(api): State<ApiState>) -> Json<ServerConfig> {
    Json(api.config)
}

/// Get the current operation mode of the light stage.
///
/// Counterpart to [`crate::api::ws::WsCommand::GetMode`]
#[utoipa::path(
    get,
    path = "/api/mode",
    tag = CONFIG_TAG,
    responses(
        (status = StatusCode::OK, description = "Get mode success", body = StageMode)
    )
)]
async fn get_mode(State(api): State<ApiState>) -> Json<StageMode> {
    Json(api.get_mode())
}

/// Set the operation mode of the light stage.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetMode`]
#[utoipa::path(
    post,
    path = "/api/mode",
    tag = CONFIG_TAG,
    responses(
        (status = StatusCode::OK, description = "Set mode success"),
        (status = StatusCode::BAD_REQUEST, description = "Invalid mode parameters", body = String)
    )
)]
async fn set_mode(State(api): State<ApiState>, Json(payload): Json<ModeRequest>) -> ApiResult<()> {
    api.set_mode(payload)?;
    Ok(())
}

/// Set the entire light stage to a uniform colour.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetLightstage`]
#[utoipa::path(
    put,
    path = "/api/manual/all",
    tag = MANUAL_TAG,
    responses(
        (status = StatusCode::OK, description = "Set entire lightstage success")
    )
)]
async fn set_lightstage(State(api): State<ApiState>, Json(payload): Json<UpdateColourRequest>) {
    api.set_lightstage(payload.rgb, payload.white);
}

/// Set an arc to a uniform colour.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetArc`]
#[utoipa::path(
    put,
    path = "/api/manual/arcs/{arc_idx}",
    tag = MANUAL_TAG,
    params(
        ("arc_idx" = u8, Path, description = "arc id")
    ),
    responses(
        (status = StatusCode::OK, description = "Set arc success"),
        (status = StatusCode::BAD_REQUEST, description = "Failure")
    )
)]
async fn set_arc(
    State(api): State<ApiState>,
    Path(arc_idx): Path<u8>,
    Json(payload): Json<UpdateColourRequest>,
) -> ApiResult<()> {
    api.set_arc(arc_idx as usize, payload.rgb, payload.white)?;
    Ok(())
}

/// Set a specific light to a colour.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetFixture`]
#[utoipa::path(
    put,
    path = "/api/manual/arcs/{arc_idx}/light/{light_idx}",
    tag = MANUAL_TAG,
    params(
        ("arc_idx" = u8, Path, description = "arc id"),
        ("light_idx" = u8, Path)
    ),
    responses(
        (status = StatusCode::OK, description = "Set fixture success"),
        (status = StatusCode::BAD_REQUEST, description = "Failure")
    )
)]
async fn set_fixture(
    State(api): State<ApiState>,
    Path((arc_idx, light_idx)): Path<(u8, u8)>,
    Json(payload): Json<UpdateColourRequest>,
) -> ApiResult<()> {
    api.set_fixture(
        arc_idx as usize,
        light_idx as usize,
        payload.rgb,
        payload.white,
    )?;
    Ok(())
}

/// Update multiple fixtures' colours.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetFixtures`]
#[utoipa::path(
    patch,
    path = "/api/manual/fixtures",
    tag = MANUAL_TAG,
    responses(
        (status = StatusCode::OK, description = "Set fixtures success"),
        (status = StatusCode::BAD_REQUEST, description = "Failure")
    )
)]
async fn set_fixtures(
    State(api): State<ApiState>,
    Json(payload): Json<Vec<UpdateFixturesRequest>>,
) -> ApiResult<()> {
    api.set_fixtures(
        payload
            .iter()
            .map(|req| (req.arc_idx, req.light_idx, req.colour.rgb, req.colour.white))
            .collect(),
    )?;
    Ok(())
}

/// Trigger a capture.
///
/// Counterpart to [`crate::api::ws::WsCommand::ManualTrigger`]
#[utoipa::path(
    post,
    path = "/api/manual/trigger",
    tag = MANUAL_TAG,
    responses(
        (status = StatusCode::OK, description = "Trigger success"),
        (status = StatusCode::BAD_REQUEST, description = "Failed to trigger cameras", body = String)
    )
)]
async fn manual_trigger(State(api): State<ApiState>) -> Result<(), (StatusCode, String)> {
    api.trigger_manual()
        .map_err(|err| (StatusCode::BAD_REQUEST, err.to_string()))
}
