//! # REST API
//!
//! This interface will provide reduced functionality as opposed to WebSocket [`crate::api::ws`],
//! which should be preferred where possible.
//!
//! All messages are encoded using JSON, such that it can be used in many contexts without
//! requiring external dependencies on CBOR (de)serialisation, as is the case with the WebSocket API.
//!
//! ## `OpenAPI` Specification
//!
//! When the server is running, the API reference (Swagger UI) can be found at
//! [`http://{host}:{port}/api-docs/swagger-ui/`][local-swagger].
//! Alternatively, rapidoc is also available under [`/api-docs/rapidoc`][local-rapidoc], or see the
//! specification itself under [`/api-docs/openapi.json`][local-spec]
//!
//! [local-swagger]: http://127.0.0.1:8080/api-docs/swagger-ui/
//! [local-rapidoc]: http://127.0.0.1:8080/api-docs/rapidoc
//! [local-spec]: http://127.0.0.1:8080/api-docs/openapi.json

use std::{net::SocketAddr, sync::Arc};

use axum::{
    Json,
    extract::{Path, State},
    http::StatusCode,
    response::IntoResponse,
    routing::any,
};
use axum_cbor::Cbor;
use serde::Deserialize;
use tokio::net::TcpListener;
use tracing::info;
use ulid::Ulid;
use utoipa::{IntoParams, IntoResponses, OpenApi};
use utoipa_axum::{router::OpenApiRouter, routes};
use utoipa_rapidoc::RapiDoc;
use utoipa_swagger_ui::SwaggerUi;

use crate::{
    api::{
        ApiState, ModeRequest, UpdateColourRequest, UpdateFixturesRequest,
        sequence::{PlaybackSequence, SequenceStore, SequenceSummary},
        ws::ws_handler,
    },
    config::ServerConfig,
    state::{SharedState, StageMode},
};

const CONFIG_TAG: &str = "Configuration";
const MANUAL_TAG: &str = "Manual Control";
const PLAYBACK_TAG: &str = "Playback Control";

/// Error type returned by some REST API handlers.
///
/// Wraps an internal error ([`anyhow::Error`])
/// and converts it into a 400 [`StatusCode::BAD_REQUEST`] response.
pub struct ApiError(pub anyhow::Error);

type ApiResult<T> = Result<T, ApiError>;

impl IntoResponse for ApiError {
    fn into_response(self) -> axum::response::Response {
        (StatusCode::BAD_REQUEST, self.0.to_string()).into_response()
    }
}

impl<E> From<E> for ApiError
where
    E: Into<anyhow::Error>,
{
    fn from(err: E) -> Self {
        Self(err.into())
    }
}

#[derive(IntoResponses)]
pub enum ApiResponses {
    /// Success
    #[response(status = StatusCode::OK)]
    Success,
    /// Failure
    #[response(status = StatusCode::BAD_REQUEST)]
    Failure(String),
}

#[derive(Deserialize, IntoParams)]
#[into_params(names("arc_idx"))]
pub struct ArcIdx(
    /// arc id
    pub u8,
);

#[derive(Deserialize, IntoParams)]
pub struct ArcLightIdx {
    /// arc id
    pub arc_idx: u8,
    /// light id
    pub light_idx: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Deserialize, IntoParams)]
#[into_params(names("id"))]
pub struct SequenceId(
    /// sequence id
    #[param(value_type = String, example = "01KYMNDBN7WWYQMPVEGTTRYHTH")]
    pub Ulid,
);

/// Autogenerated `OpenAPI` docs.
#[derive(OpenApi)]
#[openapi(info(title = "Light Stage API", description = include_str!("README.md")))]
struct ApiDoc;

/// Starts the REST (and WebSocket) API.
///
/// Creates the [`axum`] router, registers REST and WS endpoints, `OpenAPI` docs.
pub async fn start_server(
    config: ServerConfig,
    state: SharedState,
    seq_store: SequenceStore,
) -> anyhow::Result<()> {
    let api_state = Arc::new(ApiState {
        state,
        config: config.clone(),
        seq_store,
    });

    let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .route("/ws", any(ws_handler))
        .routes(routes!(get_config))
        .routes(routes!(get_mode, set_mode))
        .routes(routes!(set_lightstage))
        .routes(routes!(set_arc))
        .routes(routes!(set_fixture))
        .routes(routes!(set_fixtures))
        .routes(routes!(manual_trigger))
        .routes(routes!(get_sequences, upload_sequence))
        .routes(routes!(get_sequence, delete_sequence))
        .split_for_parts();

    // host swagger / rapidocs
    let app = router
        .merge(SwaggerUi::new("/api-docs/swagger-ui").url("/api-docs/openapi.json", api))
        // the swagger router is already hosting the openapi spec so we can just do:
        .merge(RapiDoc::new("/api-docs/openapi.json").path("/api-docs/rapidoc"))
        // if we drop swagger we would otherwise do:
        // .merge(RapiDoc::with_url(
        //     "/rapidoc",
        //     "/apid-docs/openapi.json",
        //     api,
        // ))
        .with_state(api_state);
    // TODO make base path (ie. `/api/`) configurable

    // from config
    let addr = SocketAddr::new(config.api_ip, config.api_port);
    info!("Starting REST API. Listening on http://{addr}");

    // serve
    let listener = TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;

    Ok(())
}

/// Get the server's configuration
///
/// Counterpart to [`crate::api::ws::WsCommand::GetConfig`]
#[utoipa::path(
    get,
    path = "/api/config",
    tag = CONFIG_TAG,
    responses(
        (status = StatusCode::OK, description = "Get config success", body = ServerConfig)
    )
)]
async fn get_config(State(api): State<Arc<ApiState>>) -> Json<ServerConfig> {
    Json(api.config.clone())
}

/// Get the current operation mode of the light stage.
///
/// Counterpart to [`crate::api::ws::WsCommand::GetMode`]
#[utoipa::path(
    get,
    path = "/api/mode",
    tag = CONFIG_TAG,
    responses(
        (status = StatusCode::OK, description = "Get mode success", body = StageMode)
    )
)]
async fn get_mode(State(api): State<Arc<ApiState>>) -> Json<StageMode> {
    Json(api.get_mode())
}

/// Set the operation mode of the light stage.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetMode`]
#[utoipa::path(
    post,
    path = "/api/mode",
    tag = CONFIG_TAG,
    responses(
        ApiResponses
    )
)]
async fn set_mode(
    State(api): State<Arc<ApiState>>,
    Json(payload): Json<ModeRequest>,
) -> ApiResult<()> {
    api.set_mode(payload)?;
    Ok(())
}

/// Set the entire light stage to a uniform colour.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetLightstage`]
#[utoipa::path(
    put,
    path = "/api/manual/all",
    tag = MANUAL_TAG,
    responses(
        (status = StatusCode::OK, description = "Set entire lightstage success")
    )
)]
async fn set_lightstage(
    State(api): State<Arc<ApiState>>,
    Json(payload): Json<UpdateColourRequest>,
) {
    api.set_lightstage(payload.rgb, payload.white);
}

/// Set an arc to a uniform colour.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetArc`]
#[utoipa::path(
    put,
    path = "/api/manual/arcs/{arc_idx}",
    tag = MANUAL_TAG,
    params(
        ArcIdx
    ),
    responses(
        ApiResponses
    )
)]
async fn set_arc(
    State(api): State<Arc<ApiState>>,
    Path(arc_idx): Path<ArcIdx>,
    Json(payload): Json<UpdateColourRequest>,
) -> ApiResult<()> {
    api.set_arc(arc_idx.0 as usize, payload.rgb, payload.white)?;
    Ok(())
}

/// Set a specific light to a colour.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetFixture`]
#[utoipa::path(
    put,
    path = "/api/manual/arcs/{arc_idx}/light/{light_idx}",
    tag = MANUAL_TAG,
    params(
        ArcLightIdx
    ),
    responses(
        ApiResponses
    )
)]
async fn set_fixture(
    State(api): State<Arc<ApiState>>,
    Path(arc_light): Path<ArcLightIdx>,
    Json(payload): Json<UpdateColourRequest>,
) -> ApiResult<()> {
    api.set_fixture(
        arc_light.arc_idx as usize,
        arc_light.light_idx as usize,
        payload.rgb,
        payload.white,
    )?;
    Ok(())
}

/// Update multiple fixtures' colours.
///
/// Counterpart to [`crate::api::ws::WsCommand::SetFixtures`]
#[utoipa::path(
    patch,
    path = "/api/manual/fixtures",
    tag = MANUAL_TAG,
    responses(
        ApiResponses
    )
)]
async fn set_fixtures(
    State(api): State<Arc<ApiState>>,
    Json(payload): Json<Vec<UpdateFixturesRequest>>,
) -> ApiResult<()> {
    api.set_fixtures(
        payload
            .iter()
            .map(|req| (req.arc_idx, req.light_idx, req.colour.rgb, req.colour.white))
            .collect(),
    )?;
    Ok(())
}

/// Trigger a capture.
///
/// Counterpart to [`crate::api::ws::WsCommand::ManualTrigger`]
#[utoipa::path(
    post,
    path = "/api/manual/trigger",
    tag = MANUAL_TAG,
    responses(
        ApiResponses
    )
)]
async fn manual_trigger(State(api): State<Arc<ApiState>>) -> ApiResult<()> {
    api.trigger_manual()?;
    Ok(())
}

/// List all sequences
///
/// Counterpart to [`crate::api::ws::WsCommand::ListSequences`]
#[utoipa::path(
    get,
    path = "/api/playback/sequences",
    tag = PLAYBACK_TAG
)]
async fn get_sequences(State(api): State<Arc<ApiState>>) -> ApiResult<Json<Vec<SequenceSummary>>> {
    let sequences = api.list_sequences()?;
    Ok(Json(sequences))
}

/// Get summary for sequence
///
/// Counterpart to [`crate::api::ws::WsCommand::GetSequence`]
#[utoipa::path(
    get,
    path = "/api/playback/sequences/{id}",
    tag = PLAYBACK_TAG,
    params(
        SequenceId
    )
)]
async fn get_sequence(
    State(api): State<Arc<ApiState>>,
    Path(id): Path<SequenceId>,
) -> ApiResult<Json<SequenceSummary>> {
    Ok(Json(api.get_sequence(id.0)?))
}

/// Upload sequence
///
/// Counterpart to [`crate::api::ws::WsCommand::UploadSequence`]
#[utoipa::path(
    post,
    path = "/api/playback/sequences",
    tag = PLAYBACK_TAG
)]
async fn upload_sequence(
    State(api): State<Arc<ApiState>>,
    Cbor(payload): Cbor<PlaybackSequence>,
) -> ApiResult<Json<SequenceSummary>> {
    let summary = tokio::task::spawn_blocking(move || api.upload_sequence(&payload)).await??;
    Ok(Json(summary))
}

/// Delete a sequence
///
/// Counterpart to [`crate::api::ws::WsCommand::DeleteSequence`]
#[utoipa::path(
    delete,
    path = "/api/playback/sequences/{id}",
    tag = PLAYBACK_TAG,
    params(
        SequenceId
    ),
    responses(
        ApiResponses
    )
)]
async fn delete_sequence(
    State(api): State<Arc<ApiState>>,
    Path(id): Path<SequenceId>,
) -> ApiResult<()> {
    api.delete_sequence(id.0)?;
    Ok(())
}
